name: 构建&上传 docker imagas

on:
  push:
    branches:
      - main
      
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: 登陆 docker hub 账号
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_URESNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 构建&上传 docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64/v8
        push: true
        tags: nan47/nginx-management
